apiVersion: batch/v1
kind: Job
metadata:
  name: calculator-job
spec:
  template:
    spec:
      containers:
      - name: calculator
        image: aschiebold/calculator:latest
      restartPolicy: Never